# Autogenerated wrapper script for TDSControl_jll for x86_64-linux-gnu-julia_version+1.12.0
export libtdscontroljl

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("TDSControl")
JLLWrappers.@declare_library_product(libtdscontroljl, "libtdscontroljl.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libtdscontroljl,
        "lib/libtdscontroljl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
