# Autogenerated wrapper script for TDSControl_jll for x86_64-w64-mingw32-julia_version+1.12.0
export libtdscontroljl

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("TDSControl")
JLLWrappers.@declare_library_product(libtdscontroljl, "libtdscontroljl.dll")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libtdscontroljl,
        "bin\\libtdscontroljl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
